### ISSUE TITLE
1_train_generator.py, name 'reconst' is not defined error

### ISSUE THREAD

**Issue by GilsangJang** [rpmsnu/PrimA6D#4]
root@modsim-X299-AORUS-MASTER:/mydata/home/modsim/Desktop/PrimA6D-main/Pose-Estimation/Pri
mA6D# python3 1_train_generator.py -o=1
1_train_generator.py:204: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if i % 2 is 0:
PyTorch Version:  1.10.0+cu111
Torchvision Version:  0.11.0+cu111
Device configuration :  cuda:0
dataset :  YCB
dataset path :  ../dataset/processed_dataset/YCB
obj :  1
batch :  50
total_epoch :  220
train: [0][   0/1840]	Time  5.135 ( 5.135)	KL 6.5890 (6.5890)	Reconst 1.6296 (1.6296)	primi 256.4328 (256.4328)	G 266.8240 (266.8240)	D_R 0.7625 (0.7625)	D_P 0.0000 (0.0000)
Traceback (most recent call last):
  File "1_train_generator.py", line 354, in <module>
    main()
  File "1_train_generator.py", line 146, in main
    train(train_dataset, model_G, optimizer_G, model_D_R, optimizer_D_R, model_D_P, optimizer_D_P, epoch, writer)
  File "1_train_generator.py", line 274, in train
    log_loss_ = log_loss(reconst_out, reconst)
NameError: name 'reconst' is not defined

i found NameError in 1_train.generator.py (variable name : reconst, line 274, 276)
Did i miss something?

**Comment by MyungHwanJeon** [comment]
I made a mistake uploading it. It has been updated now, so please check it out.
