### ISSUE TITLE
Reproducing PrimA6D++ w/ Graph Opt results in the YCB-Video dataset

### ISSUE THREAD

**Issue by lastflowers** [rpmsnu/PrimA6D#5]
Hi, thank you very much for sharing such a great work!

Following the instruction, I manage to run "Object-SLAM for Multi-Object Pose Optimization" example with the franka sample dataset, thank you!

I'd like to reproduce results of PrimA6D++ w/ Graph Opt in TABLE II of the paper.  But, it seems that a particular YCB-Video input files for the data_processor package looks missing to execute run_ycbv.launch. Did I miss something? 

I would appreciate any advices!

**Comment by MyungHwanJeon** [comment]
Hello, lastflowers.

Unfortunately, we accidentally removed the processed YCB-Video data which is converted to a format fitted to multi-object pose optimization. So to execute the multi-object pose optimization with YCB-Video, you have to convert the data to a specific format like seq1.zip in the data_processor repo. We recommend you refer to the data_processor repo converting data. As an alternative way, please wait for. We will recover the data soon.

Thank you.

**Comment by MyungHwanJeon** [comment]
Hi, lastflowers.

We recovered the data quickly. So you can be available on this link (https://drive.google.com/file/d/1ldXHxS7zMdF6YkyJhNQ0XPg5ANHJzGrF/view?usp=sharing).
However, the file size is so large. we had inevitably uploaded only one sequence, YCB_48.
If you want all data sequences of YCB-Video, please send mail to me. As I know from your profile, we are in the same workplace. So I will let you know my office address. 

Thank you.

**Comment by lastflowers** [comment]
Hi, thank you very much.

I ran the YCB-48 file, and it seems that there's no problem.
I will email you to get the rest of the input files, if you don't mind.

Thanks!
